apiVersion: v1
kind: Service
metadata:
  name: gameops-service
spec:
  selector:
    app: gameops
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007